[package]
name = "aoc25"
version = "0.1.0"
edition = "2024"

[dependencies]
num-traits = "0.2.19"
itertools = "0.14.0"
rand = "0.9.2"
anyhow = "1.0.100"
yansi = "1.0.1"

[profile.release]
debug = true
